# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ingestion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ingestion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fingestion.proto\x12\tingestion\"\x96\x01\n\rListenRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08track_id\x18\x03 \x01(\t\x12\x1a\n\x12\x64uration_played_ms\x18\x04 \x01(\x05\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\x12\x10\n\x08platform\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\"2\n\x0eListenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2X\n\x13SoundChainIngestion\x12\x41\n\nSendListen\x12\x18.ingestion.ListenRequest\x1a\x19.ingestion.ListenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ingestion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTENREQUEST']._serialized_start=31
  _globals['_LISTENREQUEST']._serialized_end=181
  _globals['_LISTENRESPONSE']._serialized_start=183
  _globals['_LISTENRESPONSE']._serialized_end=233
  _globals['_SOUNDCHAININGESTION']._serialized_start=235
  _globals['_SOUNDCHAININGESTION']._serialized_end=323
# @@protoc_insertion_point(module_scope)
