# Generated by Django 6.0 on 2025-12-22 14:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prev_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('hash', models.CharField(blank=True, max_length=64, null=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='ledger.account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debits', to='ledger.account')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['reference_id'], name='ledger_post_referen_86fc0a_idx'), models.Index(fields=['created_at'], name='ledger_post_created_37819c_idx')],
            },
        ),
    ]
